# Generated by Django 3.1.3 on 2020-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0004_auto_20201127_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='media/product_images/%Y/%m/%d'),
        ),
    ]
