# Generated by Django 3.1.3 on 2020-11-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0008_auto_20201127_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product-images/%Y/%m/%d/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estore.products')),
            ],
        ),
    ]
