# Generated by Django 3.1.3 on 2020-11-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0010_auto_20201127_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estore.products')),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
        migrations.DeleteModel(
            name='AdditionalImages',
        ),
    ]
