# Generated by Django 3.1.3 on 2020-11-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0011_auto_20201128_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='product-images/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
