# Generated by Django 3.1.3 on 2020-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0012_auto_20201128_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='main',
            field=models.ImageField(blank=True, upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(blank=True, upload_to='product-images'),
        ),
    ]
