# Generated by Django 3.1.3 on 2020-11-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0013_auto_20201129_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='main',
        ),
    ]
